name: freesk8_mobile
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  platform: ^3.1.0

  flutter_blue: 0.8.0 #https://pub.dev/packages/flutter_blue/changelog
  shared_preferences: 2.0.9 #https://pub.dev/packages/shared_preferences/changelog

  geolocator: ^8.2.0 #https://pub.dev/packages/geolocator/changelog

  flutter_map: #0.14.0 #https://pub.dev/packages/flutter_map/changelog
    #TODO: Change to release package when updated from 0.14.0
    git:
      url: git@github.com:FreeSK8/flutter_map.git
      ref: master

  flutter_polyline_points: 1.0.0 #https://pub.dev/packages/flutter_polyline_points/changelog

  intl: ^0.17.0 #https://pub.dev/packages/intl/changelog

  image_picker: 0.8.4+4 #https://pub.dev/packages/image_picker/changelog
  path_provider: 2.0.7 #https://pub.dev/packages/path_provider/changelog

  charts_flutter: #0.12.0 #https://pub.dev/packages/charts_flutter/changelog
      git:
        url: https://github.com/fzyzcjy/charts.git
        ref: master
        path: charts_flutter

  sliding_up_panel: ^2.0.0+1 #https://pub.dev/packages/sliding_up_panel/changelog

  esys_flutter_share: #^1.0.2 #https://pub.dev/packages/esys_flutter_share/changelog
    #TODO: Change to release package when updated from 1.0.2
    git:
      url: git@github.com:FreeSK8/esys-flutter-share.git
      ref: nullsafety+embedding-2

  wakelock: 0.5.6 #https://pub.dev/packages/wakelock/changelog

  multiselect_formfield: ^0.1.7 #https://pub.dev/packages/multiselect_formfield/changelog

  table_calendar: ^2.3.3 #https://pub.dev/packages/table_calendar/changelog #TODO: Update to 3.0.3

  flutter_nordic_dfu: #^3.0.0 #https://pub.dev/packages/flutter_nordic_dfu/changelog
    #TODO: Change to release package when updated from 3.0.0
    git:
      url: git@github.com:fengqiangboy/flutter-nordic-dfu.git
      ref: master

  wifi_iot: ^0.3.10 #https://pub.dev/packages/wifi_iot/changelog

  logger_flutter:
    #path: ../forked_packages/logger_flutter
    git:
      url: git@github.com:FreeSK8/logger_flutter.git
      ref: freesk8_mobile

  device_info_plus: ^3.2.2 #https://pub.dev/packages/device_info_plus/changelog

  duration_picker: ^1.0.1

  sqflite: 2.0.1 #https://pub.dev/packages/sqflite/changelog

  archive: ^3.1.2 #https://pub.dev/packages/archive/changelog

  flutter_document_picker: ^5.1.0 #https://pub.dev/packages/flutter_document_picker/changelog

  url_launcher: ^6.0.17 #https://pub.dev/packages/url_launcher/changelog

  uuid: 3.0.4 #https://pub.dev/packages/uuid/changelog

  flutter_slidable: ^0.6.0 #https://pub.dev/packages/flutter_slidable/changelog #TODO: Update to 1.1.0

  signal_strength_indicator: ^0.4.0 #https://pub.dev/packages/signal_strength_indicator/changelog

  flutter_spinkit: ^5.1.0 #https://pub.dev/packages/flutter_spinkit/changelog

  image: ^3.0.8 #https://pub.dev/packages/image/changelog

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.9.0 #https://pub.dev/packages/flutter_launcher_icons/changelog

#android can use transparent BG
#ios use whiteBG
flutter_icons:
  android: true
  ios: true
  image_path: "assets/FreeSK8_Icon_WhiteBG.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/FreeSK8_Icon.png
    - assets/FreeSK8_Icon_Dark.png
    - assets/firmware/Robogotchi_0.10.2.zip
    - assets/robogotchi_render.png
    - assets/FreeSK8_Mobile.png
    - assets/FreeSK8_MobileLogo.png
    - assets/map_fault.png
    - assets/map_start.png
    - assets/map_end.png
    - assets/map_position.png
    - assets/map_selection.png
    - assets/map_top_speed.png
    - assets/map_max_amps.png
    - assets/map_max_temp.png
    - assets/map_efficiency.png
    - assets/dri_about.png
    - assets/dri_icon.png
    - assets/dri_about_serious.gif
    - assets/butt.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages