name: freesk8_mobile
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: 0.8.0 #https://pub.dev/packages/flutter_blue/changelog
  shared_preferences: 0.5.7 #https://pub.dev/packages/shared_preferences/changelog

  geolocator: ^5.3.2+2
  #background_locator: 1.1.3+1
  #location_permissions: ^2.0.5

  flutter_map: 0.12.0 #https://pub.dev/packages/flutter_map/changelog
  rxdart: '>=0.18.1'

  flutter_polyline_points: 0.2.6 #https://pub.dev/packages/flutter_polyline_points/changelog

  flutter_thermometer: ^1.0.0
  flutter_gauge:
    git:
      url: git@github.com:FreeSK8/flutter_gauge.git
      ref: freesk8_mobile

  oscilloscope: 0.0.3
  intl: ^0.16.1

  image_picker: 0.7.0 #https://pub.dev/packages/image_picker/changelog
  path_provider: 1.6.7 #https://pub.dev/packages/path_provider/changelog

  charts_flutter: 0.10.0
  sliding_up_panel: ^1.0.2
  #this one does not support files# share: 0.6.4+2
  esys_flutter_share: ^1.0.2 #https://pub.dev/packages/esys_flutter_share/changelog

  wakelock: 0.1.4+1

  multiselect_formfield: ^0.1.3

  table_calendar: ^2.3.3 #https://pub.dev/packages/table_calendar/changelog

  flutter_nordic_dfu: ^2.4.0

  get_ip: ^0.4.0

  logger_flutter:
    #path: ../forked_packages/logger_flutter
    git:
      url: git@github.com:FreeSK8/logger_flutter.git
      ref: freesk8_mobile

  device_info: ^1.0.0

  duration_picker: ^1.0.1

  sqflite: 2.0.0+3 #https://pub.dev/packages/sqflite/changelog

  archive: ^3.1.2 #https://pub.dev/packages/archive/changelog

  flutter_document_picker: ^4.0.1 #https://pub.dev/packages/flutter_document_picker/changelog

  url_launcher: ^6.0.3 #https://pub.dev/packages/url_launcher/changelog

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.9.0 #https://pub.dev/packages/flutter_launcher_icons/changelog

#android can use transparent BG
#ios use whiteBG
flutter_icons:
  android: true
  ios: true
  image_path: "assets/FreeSK8_Icon_WhiteBG.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/FreeSK8_Icon.png
    - assets/firmware/Robogotchi_0.10.1.zip
    - assets/robogotchi_render.png
    - assets/FreeSK8_Mobile.jpg
    - assets/FreeSK8_MobileLogo.png
    - assets/map_fault.png
    - assets/map_start.png
    - assets/map_end.png
    - assets/map_position.png
    - assets/map_selection.png
    - assets/map_top_speed.png
    - assets/map_max_amps.png
    - assets/map_max_temp.png
    - assets/map_efficiency.png
    - assets/dri_about.png
    - assets/dri_icon.png
    - assets/dri_about_serious.gif
    - assets/butt.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages