import 'dart:typed_data';

import '../appConf.dart';
import '../mcConf.dart';

/// Reads and writes the motor (MCCONF) and app (APPCONF) configuration of one
/// firmware version. Implementations are generated by
/// tool/esc_serializers/generate.py from the firmware's confgenerator.c.
abstract class EscConfigSerializer {
  int get mcconfSignature;
  int get appconfSignature;

  /// Serialized sizes in bytes including the 4-byte signature and excluding
  /// the leading packet-id byte the ESC prepends when it sends a configuration.
  int get mcconfSize;
  int get appconfSize;

  /// [buffer] is the received payload: packet id at byte 0, signature at 1..4.
  /// Returns a configuration with `isValid == false` on a signature mismatch.
  MCCONF processMCCONF(Uint8List buffer);
  ByteData serializeMCCONF(MCCONF conf);
  APPCONF processAPPCONF(Uint8List buffer);
  ByteData serializeAPPCONF(APPCONF conf);
}
